/*
 * Copyright (c) 2016 TypeFox GmbH (http://www.typefox.io) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
grammar org.eclipse.xtext.ide.tests.testlanguage.PartialSerializationTestLanguage
with org.eclipse.xtext.common.Terminals

generate partialSerializationTestLanguage
"http://www.eclipse.org/xtext/ide/tests/testlanguage/PartialSerializationTestLanguage"

Model:
	Value | "#2" Node;

Value:
	"#1" name=ID;

Node:
	name=ID ("{" children+=Node* ("ref" ref=[Node|QualifiedName])? "}" | ";");

QualifiedName:
	ID ("." ID)*;